### PR TITLE
Disable insertable streams by default

### LINKED ISSUE #263: Aw Snap! in Chrome
Hi, we recently (per haps a month) experience crashing tabs in Chromium based browsers while using Peer Calls in mesh mode.
The crashes happen in the browser of a second client entering the room, about 1.5s after page load, less than 1s after the peer video streams appear correctly in both clients. Most often reproducable when the second client is a Chromebook, but also on Windows systems using latest Chrome (100+), say 1 in 10 reloads. In Chrome on Windows the tab says Aws Snap! STATUS_ACCESS_VIOLATION, on a Chromebook it is a SIGSEGV.

WinDebug'ging the state does not give me any clue. Updating webrtc-adapter.js to latest 8.1 (which includes latest sdp) also didn't help. I searched through its issues as github, as well as those of simplepeer, and bugs.chromium.org (webrtc), but found nothing comparable. I also changed into using Google's stun server, turning of turn(s), etc. but doesn't matter. Disabling hardware acceleration, --disable-dev-shm-usage, etc. doesn;t help either.

Since the peercalls website switched to sfu I cannot reproduce it over there. I hope you are willing to try to reproduce in a mesh setup. It demands patience filling out the forms every retry, if you are unable to reproduce quick enough please send me an email at dverspuij with domain cnsconnect dot nl, I can send you two urls with which two peers can enter a room instantly.
Alternatively I can post or send you chrome_debug logs and peer calls server logs (with mesh sdp payloads) available for both a successful and crashed connection. They mostly hint towards differing sdp's (less tcp candidates for success) and less audio stuff for failure. It may have to do with setting up or handling of the audio streams? I did turn of the VUmeter and audio processing, but didn't help either.

Thanks!

### PR DESCRIPTION
**Pull request by jeremija**
Chrome started crashing with SIGSEGV when insertable streams were
enabled in Mesh network mode. Since the insertable streams only really
work on Chrome, it did not make sense to keep it enabled by default.
Also, the insertable streams currently only works with VP8 codec, it's
broken when using the H264, which is the default when SFU mode is
enabled.

Users who wish to enable insertable streams can do so by explicitly
setting the following environment variable:

    PEERCALLS_FRONTEND_ENCODED_INSERTABLE_STREAMS=true

Or the following YAML config option:

    frontend.encodedInsertableStreams: true

This is why corporations build their own native clients if they want to
support additional features.

Closes #263.

### CODE REVIEW

**Comment by prologic** [comment]
For those of us that are a bit n00b(ish) to WebRTC in general, what's an "insertable stream"? 😅

**Comment by jeremija** [comment]
It's an API currently implemented only by Chrome which allows stream frame modifications before the audio/video data is sent over the wire to the peer on the other side.

This allows us to implement end to end encryption. This is more relevant in SFU mode because WebRTC connections are already encrypted using DTLS. In SFU mode, however, the server acts as a middleman and can intercept raw audio/video data.

Unfortunately, the only browser that supports insertable streams as of now is Chrome/Chromium so the support is limited.

**Comment by prologic** [comment]
So disabling this will have no impact on e2e encrypted audio/video streams in Mesh or Mesh+TURN configurations?

**Comment by jeremija** [comment]
That's right. And previously it required the users to pre set a password manually so it wasn't really enabled by default.

**Pull request merged**
